Repository axa-ch/json-logic-js, pull requests merged in 2020-01, with the labels that each got.

#20 Docs/add contributing file
  .huskyrc
  .lintstagedrc
  CONTRIBUTING.md
  README.md
  commitlint.config.js
  package.json
  tests/ajv4.js
  tests/tests.js
Labels: enhancement

#21 Feat/upgraded outdated deps
  package.json
Labels: enhancement

#22 Fix typo in subtract and add LF handling for Windows
  .gitattributes
  .prettierrc
  .releaserc
  package.json
  schemas/common/all-operators.json
  schemas/operators/arithmetic/subtract.json
  src/operations/arithmetic/index.js
  src/operations/arithmetic/substract.js
  src/operations/arithmetic/subtract.js
Labels: bug, enhancement

#23 docs: moved git hooks below CI/CD
  .travis.yml
  CONTRIBUTING.md
Labels: bug
